export type ProductCategory =
  | "Bumpers"
  | "Fenders"
  | "Headlights"
  | "Tail Lights"
  | "Bonnets"
  | "Mirrors"
  | "Grilles"
  | "Body Panels"
  | "Wheels"
  | "Brakes"
  | "Engine"
  | "Exhaust"
  | "Lighting";

export type ProductCondition = "New" | "Used" | "OEM" | "Aftermarket";

export type Product = {
  slug: string;
  name: string;
  brand: string;
  model: string;
  year?: string;
  category: ProductCategory;
  condition: ProductCondition;
  price: number;
  oldPrice?: number;
  discount?: string;
  rating: number;
  reviews: number;
  stock: number;
  availability: string;
  image: string;
  gallery?: string[];
  description: string;
  specs: { label: string; value: string }[];
  fitment?: string[];
  tags?: string[];
  featured?: boolean;
  trending?: boolean;
};

const PARTS_IMG = {
  bumper: "https://commons.wikimedia.org/wiki/Special:FilePath/Bumpers%20(4982843667).jpg?width=1200",
  headlight: "https://commons.wikimedia.org/wiki/Special:FilePath/2007%20GMC%20Yukon%20XL%20Headlights.jpg?width=1200",
  fender: "https://commons.wikimedia.org/wiki/Special:FilePath/1935%20Chrysler%20Deluxe%20left%20front%20fender%20(cropped).jpg?width=1200",
  taillight: "https://commons.wikimedia.org/wiki/Special:FilePath/Red%20car%20tail%20light%20(Unsplash).jpg?width=1200",
  grille: "https://commons.wikimedia.org/wiki/Special:FilePath/BMW%20kidney%20grille%2020170524.jpg?width=1200",
  mirror: "https://commons.wikimedia.org/wiki/Special:FilePath/Wing%20mirror.jpg?width=1200",
  bonnet: "https://commons.wikimedia.org/wiki/Special:FilePath/1949%20Mercury%202-door%20coupe%20hood%20.jpg?width=1200",
  foglight: "https://commons.wikimedia.org/wiki/Special:FilePath/Mercedes%20S-Class%20LED%20Tail%20Light%20(W222).jpg?width=1200",
  wheel: "https://commons.wikimedia.org/wiki/Special:FilePath/Car%20wheel%20rim%20with%20tire.jpg?width=1200",
  tire: "https://commons.wikimedia.org/wiki/Special:FilePath/Car%20tires%20as%20fenders.jpg?width=1200",
  brake: "https://commons.wikimedia.org/wiki/Special:FilePath/Disc%20brake%20dsc03682.jpg?width=1200",
  engine: "https://commons.wikimedia.org/wiki/Special:FilePath/Engine%20bay.jpg?width=1200",
  exhaust: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=82",
  oil: "https://images.unsplash.com/photo-1621786030484-4c855eed6974?auto=format&fit=crop&w=1200&q=82",
  bodypanel: "https://commons.wikimedia.org/wiki/Special:FilePath/Car%20body%20with%20front%20and%20rear%20bumper.jpg?width=1200",
};

export const PRODUCTS: Product[] = [
  {
    slug: "toyota-corolla-front-bumper",
    name: "Toyota Corolla Front Bumper",
    brand: "Toyota",
    model: "Corolla",
    year: "2020-2024",
    category: "Bumpers",
    condition: "Aftermarket",
    price: 2450,
    oldPrice: 2890,
    discount: "-15%",
    rating: 5,
    reviews: 24,
    stock: 8,
    availability: "In stock",
    image: PARTS_IMG.bumper,
    gallery: [PARTS_IMG.bumper, PARTS_IMG.bodypanel, PARTS_IMG.grille],
    description: "Paint-ready replacement front bumper for Toyota Corolla and Corolla Quest repairs. Checked for clean mounting points before quoting.",
    specs: [
      { label: "Fitment", value: "Corolla 2020-2024" },
      { label: "Material", value: "Polypropylene" },
      { label: "Finish", value: "Primer, paint ready" },
      { label: "Mounting", value: "OEM brackets included" },
    ],
    fitment: ["Toyota Corolla Sedan", "Toyota Corolla Quest"],
    tags: ["Featured"],
    featured: true,
  },
  {
    slug: "vw-polo-headlight-assembly",
    name: "VW Polo Headlight",
    brand: "Volkswagen",
    model: "Polo",
    year: "2018-2024",
    category: "Headlights",
    condition: "OEM",
    price: 1890,
    oldPrice: 2190,
    discount: "-14%",
    rating: 5,
    reviews: 18,
    stock: 3,
    availability: "Low stock",
    image: PARTS_IMG.headlight,
    gallery: [PARTS_IMG.headlight, PARTS_IMG.foglight],
    description: "OEM replacement headlight for VW Polo and Polo Vivo fitments. Side confirmed during quote before dispatch.",
    specs: [
      { label: "Fitment", value: "Polo 2018-2024" },
      { label: "Type", value: "Halogen H7" },
      { label: "Side", value: "Left / Right" },
      { label: "E-mark", value: "Certified" },
    ],
    fitment: ["VW Polo 6R", "VW Polo 6C"],
    featured: true,
  },
  {
    slug: "bmw-3-series-fender",
    name: "BMW 3 Series Fender",
    brand: "BMW",
    model: "3 Series",
    year: "F30 / F31",
    category: "Fenders",
    condition: "Used",
    price: 3200,
    oldPrice: 3750,
    discount: "-15%",
    rating: 4,
    reviews: 9,
    stock: 2,
    availability: "Quote today",
    image: PARTS_IMG.fender,
    gallery: [PARTS_IMG.fender, PARTS_IMG.bodypanel],
    description: "Used BMW F30 / F31 fender panel for collision repairs. Straight panel, ready for inspection and respray.",
    specs: [
      { label: "Fitment", value: "F30 / F31" },
      { label: "Side", value: "Right" },
      { label: "Condition", value: "Used - grade B" },
      { label: "Colour", value: "Alpine White (resprayable)" },
    ],
    fitment: ["BMW 320i", "BMW 328i", "BMW 330i", "BMW 335i"],
    featured: true,
  },
  {
    slug: "ford-ranger-led-tail-light",
    name: "Ford Ranger Tail Light",
    brand: "Ford",
    model: "Ranger",
    year: "2016-2022",
    category: "Tail Lights",
    condition: "New",
    price: 1320,
    oldPrice: 1580,
    discount: "-16%",
    rating: 5,
    reviews: 32,
    stock: 8,
    availability: "In stock",
    image: PARTS_IMG.taillight,
    gallery: [PARTS_IMG.taillight],
    description: "Smoked lens LED tail light upgrade for Ford Ranger T6/T7. Plug-and-play with OEM harness, integrated indicator and reverse cluster.",
    specs: [
      { label: "Fitment", value: "Ranger T6 / T7" },
      { label: "Type", value: "LED cluster" },
      { label: "Lens", value: "Smoked" },
      { label: "Warranty", value: "12 months" },
    ],
    fitment: ["Ford Ranger T6", "Ford Ranger T7"],
    featured: true,
  },
  {
    slug: "mercedes-c-class-grille",
    name: "Mercedes C-Class Grille",
    brand: "Mercedes-Benz",
    model: "C-Class",
    year: "2015-2019",
    category: "Grilles",
    condition: "OEM",
    price: 4100,
    oldPrice: 4650,
    discount: "-12%",
    rating: 5,
    reviews: 14,
    stock: 1,
    availability: "Low stock",
    image: PARTS_IMG.grille,
    gallery: [PARTS_IMG.grille],
    description: "OEM Mercedes C-Class W205 front grille with chrome star surround. Direct fit, no modification required.",
    specs: [
      { label: "Fitment", value: "W205" },
      { label: "Finish", value: "Chrome star + gloss black" },
      { label: "Part type", value: "OEM" },
    ],
    fitment: ["Mercedes C200", "Mercedes C220d", "Mercedes C250", "Mercedes C300"],
    featured: true,
  },
  {
    slug: "hyundai-i20-side-mirror",
    name: "Hyundai i20 Side Mirror",
    brand: "Hyundai",
    model: "i20",
    year: "2015-2020",
    category: "Mirrors",
    condition: "Aftermarket",
    price: 980,
    oldPrice: 1190,
    discount: "-18%",
    rating: 4,
    reviews: 11,
    stock: 15,
    availability: "In stock",
    image: PARTS_IMG.mirror,
    gallery: [PARTS_IMG.mirror],
    description: "Powered folding side mirror for Hyundai i20, passenger or driver side. Heated option, indicator repeater included.",
    specs: [
      { label: "Fitment", value: "i20 GB/PB" },
      { label: "Function", value: "Electric fold + heat" },
      { label: "Indicator", value: "Built-in" },
    ],
    fitment: ["Hyundai i20 GB", "Hyundai i20 PB"],
    featured: true,
  },
  {
    slug: "toyota-corolla-bonnet",
    name: "Toyota Corolla Bonnet Panel",
    brand: "Toyota",
    model: "Corolla",
    year: "2014-2018",
    category: "Bonnets",
    condition: "New",
    price: 2450,
    oldPrice: 2899,
    discount: "-14%",
    rating: 5,
    reviews: 7,
    stock: 4,
    availability: "In stock",
    image: PARTS_IMG.bonnet,
    gallery: [PARTS_IMG.bonnet],
    description: "Brand new Corolla bonnet panel, factory primed. Ready for paintwork.",
    specs: [
      { label: "Fitment", value: "Corolla E160/E170" },
      { label: "Material", value: "Steel" },
      { label: "Finish", value: "Primer" },
    ],
    fitment: ["Toyota Corolla E170"],
    featured: true,
  },
  {
    slug: "universal-fog-light-kit",
    name: "Universal LED Fog Light Kit",
    brand: "Universal",
    model: "Universal",
    category: "Lighting",
    condition: "New",
    price: 720,
    oldPrice: 899,
    discount: "-20%",
    rating: 4,
    reviews: 52,
    stock: 20,
    availability: "In stock",
    image: PARTS_IMG.foglight,
    gallery: [PARTS_IMG.foglight],
    description: "Universal LED fog light kit with switch, harness, and brackets. Fits most vehicles.",
    specs: [
      { label: "Type", value: "LED 18W" },
      { label: "Voltage", value: "12V" },
      { label: "Beam", value: "Spot + flood" },
      { label: "Kit", value: "2x lamps + harness + switch" },
    ],
    featured: true,
  },
  {
    slug: "altra-brake-rotor-front",
    name: "Altra Industrial Front Brake Rotor",
    brand: "Universal",
    model: "Universal",
    category: "Brakes",
    condition: "New",
    price: 480,
    oldPrice: 599,
    discount: "-20%",
    rating: 5,
    reviews: 44,
    stock: 16,
    availability: "In stock",
    image: PARTS_IMG.brake,
    gallery: [PARTS_IMG.brake],
    description: "Vented front brake rotor with anti-corrosion coating. Sold as pair.",
    specs: [
      { label: "Type", value: "Vented" },
      { label: "Diameter", value: "296mm" },
      { label: "Sold as", value: "Pair" },
    ],
    trending: true,
  },
  {
    slug: "brembo-gt-brake-pads",
    name: "Brembo GT Performance Brake Pads",
    brand: "Universal",
    model: "Universal",
    category: "Brakes",
    condition: "New",
    price: 1850,
    oldPrice: 2150,
    discount: "-14%",
    rating: 5,
    reviews: 28,
    stock: 7,
    availability: "In stock",
    image: PARTS_IMG.engine,
    gallery: [PARTS_IMG.engine],
    description: "High-performance Brembo GT brake pad set. Low dust, low noise, track-tested.",
    specs: [
      { label: "Compound", value: "Low-metallic" },
      { label: "Temp range", value: "0-650°C" },
      { label: "Sold as", value: "Axle set" },
    ],
    trending: true,
  },
  {
    slug: "driver-side-halogen-headlight",
    name: "Driver Side Halogen Headlight",
    brand: "Universal",
    model: "Universal",
    category: "Headlights",
    condition: "New",
    price: 1150,
    oldPrice: 1299,
    discount: "-12%",
    rating: 4,
    reviews: 19,
    stock: 12,
    availability: "In stock",
    image: PARTS_IMG.headlight,
    gallery: [PARTS_IMG.headlight],
    description: "Universal driver-side halogen headlight replacement. Multiple fitments available — contact for match.",
    specs: [
      { label: "Type", value: "Halogen" },
      { label: "Side", value: "Driver" },
    ],
    trending: true,
  },
  {
    slug: "racing-custom-wheels-18",
    name: "18 inch Racing Custom Alloy Wheels",
    brand: "Universal",
    model: "Universal",
    category: "Wheels",
    condition: "New",
    price: 4200,
    oldPrice: 4800,
    discount: "-13%",
    rating: 5,
    reviews: 61,
    stock: 4,
    availability: "Set of 4",
    image: PARTS_IMG.wheel,
    gallery: [PARTS_IMG.wheel, PARTS_IMG.tire],
    description: "18 inch multi-spoke alloy wheels, matte black finish with polished lip. Sold as set of 4.",
    specs: [
      { label: "Diameter", value: "18 inch" },
      { label: "PCD", value: "5x112" },
      { label: "Finish", value: "Matte black / polished" },
      { label: "Set", value: "4 wheels" },
    ],
    trending: true,
  },
  {
    slug: "duck-stack-muffler",
    name: "Duck Stack Performance Muffler",
    brand: "Universal",
    model: "Universal",
    category: "Exhaust",
    condition: "New",
    price: 2950,
    oldPrice: 3499,
    discount: "-15%",
    rating: 4,
    reviews: 22,
    stock: 5,
    availability: "In stock",
    image: PARTS_IMG.exhaust,
    gallery: [PARTS_IMG.exhaust],
    description: "Stainless steel performance muffler with deep, aggressive tone. Bolt-on fitment.",
    specs: [
      { label: "Material", value: "Stainless steel" },
      { label: "Inlet", value: "2.5 inch" },
      { label: "Finish", value: "Brushed" },
    ],
    trending: true,
  },
  {
    slug: "brembo-gt-caliper-kit",
    name: "Brembo GT Big Brake Caliper Kit",
    brand: "Universal",
    model: "Universal",
    category: "Brakes",
    condition: "New",
    price: 12500,
    oldPrice: 14800,
    discount: "-15%",
    rating: 5,
    reviews: 8,
    stock: 2,
    availability: "Limited",
    image: PARTS_IMG.foglight,
    gallery: [PARTS_IMG.foglight],
    description: "Brembo GT 4-piston big brake upgrade kit. Includes calipers, pads, rotors, and lines.",
    specs: [
      { label: "Pistons", value: "4" },
      { label: "Rotor", value: "355mm" },
      { label: "Finish", value: "Red" },
    ],
    trending: true,
  },
  {
    slug: "car-wheel-rim-17",
    name: "17 inch Alloy Wheel & Rim",
    brand: "Universal",
    model: "Universal",
    category: "Wheels",
    condition: "New",
    price: 3400,
    oldPrice: 3800,
    discount: "-10%",
    rating: 4,
    reviews: 17,
    stock: 6,
    availability: "Set of 4",
    image: PARTS_IMG.tire,
    gallery: [PARTS_IMG.tire, PARTS_IMG.wheel],
    description: "17 inch five-spoke alloy rims. Sold as set.",
    specs: [
      { label: "Diameter", value: "17 inch" },
      { label: "Finish", value: "Silver" },
    ],
    trending: true,
  },
  {
    slug: "strut-assembly-front",
    name: "Front Strut & Coilover Assembly",
    brand: "Universal",
    model: "Universal",
    category: "Engine",
    condition: "New",
    price: 2650,
    oldPrice: 3100,
    discount: "-14%",
    rating: 5,
    reviews: 13,
    stock: 6,
    availability: "In stock",
    image: PARTS_IMG.brake,
    gallery: [PARTS_IMG.brake],
    description: "Complete front strut assembly. Bolt-on, no spring compression required.",
    specs: [
      { label: "Type", value: "Assembled strut" },
      { label: "Sold as", value: "Each" },
    ],
  },
  {
    slug: "engine-cooling-fan",
    name: "Engine Cooling Fan Assembly",
    brand: "Universal",
    model: "Universal",
    category: "Engine",
    condition: "New",
    price: 1450,
    oldPrice: 1799,
    discount: "-19%",
    rating: 4,
    reviews: 9,
    stock: 4,
    availability: "In stock",
    image: PARTS_IMG.engine,
    gallery: [PARTS_IMG.engine],
    description: "Replacement radiator cooling fan assembly with shroud and motor.",
    specs: [
      { label: "Voltage", value: "12V" },
      { label: "Mount", value: "Bolt-on" },
    ],
  },
  {
    slug: "h7-hid-xenon-kit",
    name: "H7 HID Xenon Conversion Kit",
    brand: "Universal",
    model: "Universal",
    category: "Lighting",
    condition: "New",
    price: 1100,
    oldPrice: 1399,
    discount: "-21%",
    rating: 4,
    reviews: 38,
    stock: 14,
    availability: "In stock",
    image: PARTS_IMG.headlight,
    gallery: [PARTS_IMG.headlight],
    description: "H7 xenon HID conversion kit with ballasts, bulbs, and harness. 6000K cool white.",
    specs: [
      { label: "Bulb", value: "H7 HID" },
      { label: "Colour", value: "6000K" },
      { label: "Ballast", value: "Slim digital" },
    ],
  },
  {
    slug: "body-panel-repair-kit",
    name: "Universal Body Panel Repair Kit",
    brand: "Universal",
    model: "Universal",
    category: "Body Panels",
    condition: "New",
    price: 1850,
    oldPrice: 2200,
    discount: "-16%",
    rating: 4,
    reviews: 6,
    stock: 8,
    availability: "In stock",
    image: PARTS_IMG.bodypanel,
    gallery: [PARTS_IMG.bodypanel],
    description: "Comprehensive body panel repair kit with filler, primer, and sanding block.",
    specs: [
      { label: "Includes", value: "Filler, primer, sander" },
    ],
  },
  {
    slug: "engine-oil-5w40-5l",
    name: "Fully Synthetic Engine Oil 5W-40 (5L)",
    brand: "Universal",
    model: "Universal",
    category: "Engine",
    condition: "New",
    price: 620,
    oldPrice: 749,
    discount: "-17%",
    rating: 5,
    reviews: 141,
    stock: 40,
    availability: "In stock",
    image: PARTS_IMG.oil,
    gallery: [PARTS_IMG.oil],
    description: "Fully synthetic 5W-40 engine oil. Meets ACEA A3/B4. 5 litre container.",
    specs: [
      { label: "Grade", value: "5W-40" },
      { label: "Spec", value: "ACEA A3/B4" },
      { label: "Volume", value: "5L" },
    ],
  },
  {
    slug: "ford-ranger-front-bumper",
    name: "Ford Ranger Front Bumper (T7)",
    brand: "Ford",
    model: "Ranger",
    year: "2019-2022",
    category: "Bumpers",
    condition: "Aftermarket",
    price: 2150,
    oldPrice: 2599,
    discount: "-17%",
    rating: 4,
    reviews: 15,
    stock: 3,
    availability: "In stock",
    image: PARTS_IMG.bumper,
    gallery: [PARTS_IMG.bumper],
    description: "Aftermarket Ford Ranger T7 front bumper cover, unpainted primer. OEM fitment.",
    specs: [
      { label: "Fitment", value: "Ranger T7" },
      { label: "Material", value: "Polypropylene" },
    ],
    fitment: ["Ford Ranger T7"],
  },
  {
    slug: "toyota-hilux-tail-light",
    name: "Toyota Hilux Tail Light Lens",
    brand: "Toyota",
    model: "Hilux",
    year: "2015-2020",
    category: "Tail Lights",
    condition: "OEM",
    price: 980,
    rating: 5,
    reviews: 21,
    stock: 10,
    availability: "In stock",
    image: PARTS_IMG.taillight,
    gallery: [PARTS_IMG.taillight],
    description: "OEM tail light lens for Toyota Hilux 3rd gen, left or right.",
    specs: [
      { label: "Fitment", value: "Hilux 2015-2020" },
      { label: "Side", value: "Left / Right" },
    ],
    fitment: ["Toyota Hilux"],
  },
  {
    slug: "bmw-3-series-kidney-grille",
    name: "BMW 3 Series Kidney Grille",
    brand: "BMW",
    model: "3 Series",
    year: "2012-2019",
    category: "Grilles",
    condition: "OEM",
    price: 1850,
    oldPrice: 2200,
    discount: "-16%",
    rating: 5,
    reviews: 33,
    stock: 5,
    availability: "In stock",
    image: PARTS_IMG.grille,
    gallery: [PARTS_IMG.grille],
    description: "OEM-style BMW kidney grille for F30/F31. Gloss black finish.",
    specs: [
      { label: "Fitment", value: "F30/F31" },
      { label: "Finish", value: "Gloss black" },
    ],
    fitment: ["BMW F30", "BMW F31"],
  },
];

export const CATEGORIES: { name: ProductCategory; image: string }[] = [
  { name: "Bumpers", image: PARTS_IMG.bumper },
  { name: "Fenders", image: PARTS_IMG.fender },
  { name: "Headlights", image: PARTS_IMG.headlight },
  { name: "Tail Lights", image: PARTS_IMG.taillight },
  { name: "Bonnets", image: PARTS_IMG.bonnet },
  { name: "Mirrors", image: PARTS_IMG.mirror },
  { name: "Grilles", image: PARTS_IMG.grille },
  { name: "Body Panels", image: PARTS_IMG.bodypanel },
  { name: "Wheels", image: PARTS_IMG.wheel },
  { name: "Brakes", image: PARTS_IMG.brake },
  { name: "Engine", image: PARTS_IMG.engine },
  { name: "Lighting", image: PARTS_IMG.foglight },
];

export const BRANDS = ["Toyota", "Volkswagen", "BMW", "Ford", "Mercedes-Benz", "Hyundai", "Universal"] as const;

export const CONDITIONS: ProductCondition[] = ["New", "Used", "OEM", "Aftermarket"];

export const FEATURE_TABS = [
  "Body Panels & Bumpers",
  "Lights & Mirrors",
  "Engine & Mechanical",
  "Trim & Accessories",
] as const;

export function getFeatured(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}

export function getTrending(): Product[] {
  return PRODUCTS.filter((p) => p.trending);
}

export function getByCategory(category: ProductCategory): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function findProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function relatedProducts(slug: string, limit = 4): Product[] {
  const p = findProduct(slug);
  if (!p) return [];
  return PRODUCTS.filter((x) => x.slug !== slug && x.category === p.category).slice(0, limit);
}
