export type Section =
  | "overview"
  | "inventory"
  | "pos"
  | "orders"
  | "conversations"
  | "escalations"
  | "suppliers"
  | "broadcast"
  | "reviews"
  | "reports"
  | "audit"
  | "notifications"
  | "faq"
  | "settings";
